version: "3"
services:
  mlflow:
    build:
      context: mlflow/
    command:
      - bash
      - -c
      - "mlflow server --backend-store-uri sqlite:////mlflow/mlflow.db --serve-artifacts --host 0.0.0.0 --port 5000"
    ports:
      - "5000:5000"
    volumes:
      - ./run_env/data:/mlflow

  nginx:
    image: nginx:latest
    restart: on-failure
    ports:
      - 5040:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
